#! /bin/sh


#----Autostart
#pgrep -x sxhkd > /dev/null || sxhkd &


#----Workspace distribution per monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10


#----BSPWM's graphical appearance
bspc config border_width         1
bspc config window_gap          10
bspc config normal_border_color "#7c818c"
bspc config active_border_color "#4c566a"
bspc config focused_border_color "#8fbcbb"
bspc config presel_feedback_color "#8fbcbb"


#----Prot's additions:
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc ignore_ewmh_focus false
_bc single_monocle false


#----BSPWM's tiling rules:
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

      
#----BSPWM's applications rules:
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Xmessage state=floating
bspc rule -a Galculator state=floating
bspc rule -a Arandr state=floating
bspc rule -a Pavucontrol state=floating rectangle=80x10
bspc rule -a Nm-connection-editor state=floating rectangle=80x10
bspc rule -a Pcmanfm state=floating rectangle=800x600u
